title: Alessandro Romei
tagline: Finance · Equity Research · Strategy
author: Alessandro Romei
description: Portfolio of Alessandro Romei — CV, posts, and research notes.
markdown: kramdown
permalink: /posts/:title/
